version: '3.4'
name: "mayz-contracts"
services:
  plutus:
    image: manupadilla/${COMPOSE_PROJECT_NAME}_dev_image:latest
    volumes:
      - ..:/home/plutus/workspace
    env_file:
      - .env
    command:  /bin/bash -c "chmod +x /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && /home/plutus/workspace/.devcontainer/scripts/on-create-container.sh && while sleep 1000; do :; done"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
